In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

# Cargar datos
data = load_iris()
X = pd.DataFrame(data.data, columns=data.feature_names)

# Centrar datos
X_centered = X - X.mean()

# Matriz de covarianza 
C = np.cov(X_centered, rowvar=False)

C

array([[ 0.68569351, -0.042434  ,  1.27431544,  0.51627069],
       [-0.042434  ,  0.18997942, -0.32965638, -0.12163937],
       [ 1.27431544, -0.32965638,  3.11627785,  1.2956094 ],
       [ 0.51627069, -0.12163937,  1.2956094 ,  0.58100626]])

# Método 1: autovalores/autovectores

In [2]:
eigvals, eigvecs = np.linalg.eig(C)

# Ordenar de mayor a menor
idx = np.argsort(eigvals)[::-1]
eigvals_sorted = eigvals[idx]
eigvecs_sorted = eigvecs[:, idx]

eigvals_sorted, eigvecs_sorted


(array([4.22824171, 0.24267075, 0.0782095 , 0.02383509]),
 array([[ 0.36138659, -0.65658877, -0.58202985,  0.31548719],
        [-0.08452251, -0.73016143,  0.59791083, -0.3197231 ],
        [ 0.85667061,  0.17337266,  0.07623608, -0.47983899],
        [ 0.3582892 ,  0.07548102,  0.54583143,  0.75365743]]))

# Método 2: PCA mediante SVD

In [3]:
U, S, Vt = np.linalg.svd(X_centered, full_matrices=False)

# Varianzas por componente
S2 = (S**2) / (X.shape[0] - 1)

# Los vectores principales están en Vt
V_svd = Vt.T

S2, V_svd


(array([4.22824171, 0.24267075, 0.0782095 , 0.02383509]),
 array([[ 0.36138659, -0.65658877,  0.58202985,  0.31548719],
        [-0.08452251, -0.73016143, -0.59791083, -0.3197231 ],
        [ 0.85667061,  0.17337266, -0.07623608, -0.47983899],
        [ 0.3582892 ,  0.07548102, -0.54583143,  0.75365743]]))

# Comparacion 

In [4]:
np.allclose(eigvals_sorted, S2)

True

In [5]:
np.allclose(np.abs(eigvecs_sorted), np.abs(V_svd))

True

Podemos que Ambos métodos producen la misma matriz de componentes principales

SVD y autovalores/autovectores son equivalentes para PCA.

Los autovalores coinciden:  4.228,0.242,0.078,0.023

Las matrices de autovectores son idénticas salvo por signo

Lo cual es normal.